"""LLM abstraction layer supporting Ollama, OpenAI-compatible, and Demo backends."""
from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from typing import Any

import httpx

from src.config import get_settings

logger = logging.getLogger(__name__)


class BaseLLM(ABC):
    """Abstract LLM interface."""

    @abstractmethod
    def generate(
        self,
        prompt: str,
        system: str | None = None,
        max_tokens: int = 1024,
        temperature: float = 0.3,
    ) -> str:
        ...

    @abstractmethod
    def is_available(self) -> bool:
        ...


class DemoLLM(BaseLLM):
    """Deterministic demo backend – no external model required."""

    def is_available(self) -> bool:
        return True

    def generate(
        self,
        prompt: str,
        system: str | None = None,
        max_tokens: int = 1024,
        temperature: float = 0.3,
    ) -> str:
        context_block = ""
        if "Context:" in prompt:
            try:
                context_block = prompt.split("Context:")[1].split("Question:")[0].strip()
            except Exception:
                context_block = ""

        question = prompt
        if "Question:" in prompt:
            question = prompt.split("Question:")[-1].strip()

        if context_block:
            return (
                "[Demo Mode Response]\n\n"
                "Based on the retrieved local knowledge base, here is a synthesized answer:\n\n"
                f"{context_block[:800]}\n\n"
                "---\n"
                "This answer was generated by the offline demo backend. "
                "To use a real open-weight model, set LLM_BACKEND=ollama and run "
                "`ollama pull llama3.2:1b` (or another supported model)."
            )
        return (
            "[Demo Mode Response]\n\n"
            f"I received your query: “{question[:200]}…”\n\n"
            "No relevant documents were retrieved from the local knowledge base. "
            "Upload documents via the UI or API and re-ask, or switch to an Ollama "
            "backend for generative answers.\n\n"
            "Demo mode is active – responses are template-based and do not require a GPU."
        )


class OllamaLLM(BaseLLM):
    """Ollama-compatible local LLM client."""

    def __init__(
        self,
        base_url: str | None = None,
        model: str | None = None,
        timeout: int | None = None,
    ) -> None:
        settings = get_settings()
        self.base_url = (base_url or settings.ollama_base_url).rstrip("/")
        self.model = model or settings.ollama_model
        self.timeout = timeout or settings.ollama_timeout

    def is_available(self) -> bool:
        try:
            with httpx.Client(timeout=5.0) as client:
                r = client.get(f"{self.base_url}/api/tags")
                return r.status_code == 200
        except Exception:
            return False

    def generate(
        self,
        prompt: str,
        system: str | None = None,
        max_tokens: int = 1024,
        temperature: float = 0.3,
    ) -> str:
        messages: list[dict[str, str]] = []
        if system:
            messages.append({"role": "system", "content": system})
        messages.append({"role": "user", "content": prompt})

        payload: dict[str, Any] = {
            "model": self.model,
            "messages": messages,
            "stream": False,
            "options": {
                "num_predict": max_tokens,
                "temperature": temperature,
            },
        }
        try:
            with httpx.Client(timeout=self.timeout) as client:
                r = client.post(f"{self.base_url}/api/chat", json=payload)
                r.raise_for_status()
                data = r.json()
                return data.get("message", {}).get("content", "") or data.get("response", "")
        except httpx.HTTPError as exc:
            logger.error("Ollama request failed: %s", exc)
            raise RuntimeError(
                f"Ollama request failed: {exc}. "
                "Ensure Ollama is running (`ollama serve`) and the model is pulled."
            ) from exc


class OpenAICompatibleLLM(BaseLLM):
    """Generic OpenAI-compatible chat completions client."""

    def __init__(
        self,
        base_url: str | None = None,
        api_key: str | None = None,
        model: str | None = None,
    ) -> None:
        settings = get_settings()
        self.base_url = (base_url or settings.openai_compatible_base_url).rstrip("/")
        self.api_key = api_key or settings.openai_compatible_api_key
        self.model = model or settings.openai_compatible_model

    def is_available(self) -> bool:
        return bool(self.base_url and self.model)

    def generate(
        self,
        prompt: str,
        system: str | None = None,
        max_tokens: int = 1024,
        temperature: float = 0.3,
    ) -> str:
        if not self.is_available():
            raise RuntimeError("OpenAI-compatible backend is not configured.")
        messages: list[dict[str, str]] = []
        if system:
            messages.append({"role": "system", "content": system})
        messages.append({"role": "user", "content": prompt})
        headers = {"Content-Type": "application/json"}
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"
        payload = {
            "model": self.model,
            "messages": messages,
            "max_tokens": max_tokens,
            "temperature": temperature,
        }
        with httpx.Client(timeout=120.0) as client:
            r = client.post(
                f"{self.base_url}/v1/chat/completions",
                json=payload,
                headers=headers,
            )
            r.raise_for_status()
            data = r.json()
            return data["choices"][0]["message"]["content"]


def get_llm() -> BaseLLM:
    """Factory that returns the configured LLM backend."""
    settings = get_settings()
    backend = settings.llm_backend
    if backend == "ollama":
        llm = OllamaLLM()
        if llm.is_available():
            return llm
        logger.warning("Ollama not available – falling back to DemoLLM")
        return DemoLLM()
    if backend == "openai_compatible":
        llm = OpenAICompatibleLLM()
        if llm.is_available():
            return llm
        logger.warning("OpenAI-compatible endpoint not configured – falling back to DemoLLM")
        return DemoLLM()
    return DemoLLM()
